"""This sub-module contains the functions that are specific to the environment."""

from isaaclab.envs.mdp import *  # noqa: F401, F403

from .rewards import (
    track_joint_pos,
    track_joint_vel,
    track_root_pos,
    track_root_quat,
    track_root_ang,
    track_root_lin_vel,
    track_root_ang_vel,
    track_relative_body_pos,
    track_relative_body_quat,
    track_relative_body_vel,
    reference_global_anchor_position_error_exp,
    reference_global_anchor_orientation_error_exp,
    reference_relative_body_position_error_exp,
    reference_relative_body_orientation_error_exp,
    reference_global_body_linear_velocity_error_exp,
    reference_global_body_angular_velocity_error_exp,
)
from .events import (
    randomize_joint_default_pos,
    reset_joints_to_reference,
    reset_root_and_joints_to_reference_with_randomization,
)
from .observations import (
    reference_motion_command,
    reference_anchor_pos_b,
    reference_anchor_ori_b,
    robot_body_pos_b,
    robot_body_ori_b,
    reference_joint_pos,
    reference_joint_vel,
    reference_root_pos,
    reference_root_lin_vel,
    reference_root_ang_vel,
    reference_root_quat,
)
from .terminations import (
    bad_anchor_pos_z_only,
    bad_anchor_ori,
    bad_reference_body_pos_z_only,
    reference_joint_pos_deviation_too_much,
    reference_root_position_xy_deviation_too_much,
    reference_root_quat_deviation_too_much,
)


__all__ = [
    "track_root_quat",
    "track_root_pos",
    "track_joint_pos",
    "track_joint_vel",
    "track_relative_body_pos",
    "track_relative_body_quat",
    "track_relative_body_vel",
    "track_root_ang",
    "track_root_lin_vel",
    "track_root_ang_vel",
    "reference_global_anchor_position_error_exp",
    "reference_global_anchor_orientation_error_exp",
    "reference_relative_body_position_error_exp",
    "reference_relative_body_orientation_error_exp",
    "reference_global_body_linear_velocity_error_exp",
    "reference_global_body_angular_velocity_error_exp",
    "randomize_joint_default_pos",
    "reset_joints_to_reference",
    "reset_root_and_joints_to_reference_with_randomization",
    "reference_motion_command",
    "reference_anchor_pos_b",
    "reference_anchor_ori_b",
    "robot_body_pos_b",
    "robot_body_ori_b",
    "reference_joint_pos",
    "reference_joint_vel",
    "reference_root_pos",
    "reference_root_lin_vel",
    "reference_root_ang_vel",
    "reference_root_quat",
    "bad_anchor_pos_z_only",
    "bad_anchor_ori",
    "bad_reference_body_pos_z_only",
    "reference_joint_pos_deviation_too_much",
    "reference_root_position_xy_deviation_too_much",
    "reference_root_quat_deviation_too_much",
]
